name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: bun install --frozen-lockfile

      - run: sudo apt-get install -y advancecomp

      - run: npm run build

      - name: deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v2
        if: success() && github.ref == 'refs/heads/master'
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
